kartoza/qgis-gea-plugin

- .github/workflows/ci.yml
- admin.py
- run-tests.sh
- scripts/docker/qgis-gea-plugin-test-pre-scripts.sh
- src/qgis_gea_plugin/conf.py
- src/qgis_gea_plugin/definitions/defaults.py
- src/qgis_gea_plugin/gui/qgis_gea.py
- src/qgis_gea_plugin/gui/qgis_gea_plugin.py
- src/qgis_gea_plugin/main.py
- src/qgis_gea_plugin/models/base.py
- src/qgis_gea_plugin/ui/main_dockwidget.ui
- src/qgis_gea_plugin/utils.py
- test/test_main_dock.py
- test_suite.py
Fixes https://github.com/kartoza/qgis-gea-plugin/issues/7
Initial implementation of the time slider functionality.
Screenshot of the played animation from the plugin slider
https://github.com/user-attachments/assets/bbf0f187-4485-4acd-be44-b1baf961080f
> Time slider implementation

- src/qgis_gea_plugin/conf.py
- src/qgis_gea_plugin/definitions/defaults.py
- src/qgis_gea_plugin/gui/qgis_gea.py
- src/qgis_gea_plugin/ui/main_dockwidget.ui
- src/qgis_gea_plugin/utils.py
Fixes https://github.com/kartoza/qgis-gea-plugin/issues/8
> Drawing tool implementation

- src/qgis_gea_plugin/gui/qgis_gea.py
- src/qgis_gea_plugin/ui/main_dockwidget.ui
Sort the time list before adding them into the time slider and added a new spin box to allow users to provide the frame rate they want.
> Updates to the time slider

- docs/mkdocs-base.yml
@ketankartoza Please update the Nav so that I can see the docs on the doc website. I have done this one sample. Please do the rest.
> Update the docs nav: Update mkdocs-base.yml

- docs/mkdocs-base.yml
- docs/mkdocs.yml
- docs/src/user/guide/reports.md
- docs/src/user/manual/reports.md
> Update mkdocs file

- src/qgis_gea_plugin/conf.py
- src/qgis_gea_plugin/gui/qgis_gea.py
Include error message when saving site layer fails and new style for the site layers in the map
> Report and site editing updates

- src/qgis_gea_plugin/gui/qgis_gea.py
- src/qgis_gea_plugin/gui/report_progress_dialog.py
- src/qgis_gea_plugin/lib/reports/generator.py
The generated report wasn't showing/including the site layer, these changes resolve the issue when fetching and styling the target site layer and includes it in the final report map items.
| Old report | New report|
|--------------|---------------|
| ![image](https://github.com/user-attachments/assets/81f146cb-f1d5-4c11-a69c-c6fc5ecd1706) | ![image](https://github.com/user-attachments/assets/a7f92e4f-d3d1-4d98-8d4c-d815e1bb1684) |
> Fix for site layer not showing up in the report

- src/qgis_gea_plugin/definitions/defaults.py
- src/qgis_gea_plugin/gui/qgis_gea.py
- src/qgis_gea_plugin/ui/main_dockwidget.ui
Fixes https://github.com/kartoza/qgis-gea-plugin/issues/93
Screenshot of the imported project instance into the project
> Support for adding project instances

- src/qgis_gea_plugin/definitions/defaults.py
- src/qgis_gea_plugin/gui/attribute_form.py
- src/qgis_gea_plugin/gui/qgis_gea.py
- src/qgis_gea_plugin/ui/attribute_form.ui
- src/qgis_gea_plugin/ui/main_dockwidget.ui
Fixes https://github.com/kartoza/qgis-gea-plugin/issues/94
Screenshot of the functionality in action
https://github.com/user-attachments/assets/779c1317-250a-4a22-ad71-b57f8feea86e
> Attribute form support for the project instances

- docs/mkdocs-base.yml
- docs/requirements.txt
> Build fix1

- docs/mkdocs-base.yml
- docs/requirements.txt
- requirements.txt
Updated the versions and added new dependencies.
Built site on my fork.
https://ketankartoza.github.io/qgis-gea-plugin/
> Build-fix documentation site

- src/qgis_gea_plugin/data/report_templates/project_instance.qpt
- src/qgis_gea_plugin/data/report_templates/reforestation_site.qpt
New report templates now include a legend.
> Updates on the report templates

- docs/src/administrator/index.md
- docs/src/developer/documentation/overview.md
- docs/src/developer/guide/architecture.md
- docs/src/developer/guide/building.md
- docs/src/developer/guide/configuration.md
- docs/src/developer/guide/ide-setup.md
- docs/src/developer/guide/workflows.md
- docs/src/user/Appendix1.md
- docs/src/user/guide/gea-reforestation-tool.md
Corrected user documents on grammar and spelling
> Documentation review (grammar and spell checks)

- src/qgis_gea_plugin/definitions/defaults.py
Updates the site layers group name from `Proposed Site Boundaries` to `Drawn Areas of Interest`
> Site group name change

- src/qgis_gea_plugin/gui/qgis_gea.py
Fixes https://github.com/kartoza/qgis-gea-plugin/issues/121
Implements changes that enable auto generation of the one drawn feature.
> Auto generation of drawn feature Id

- src/qgis_gea_plugin/ui/main_dockwidget.ui
Fixes https://github.com/kartoza/qgis-gea-plugin/issues/125
Screenshot
> New location for the report generation button

- src/qgis_gea_plugin/definitions/defaults.py
- src/qgis_gea_plugin/gui/qgis_gea.py
Fixes https://github.com/kartoza/qgis-gea-plugin/issues/126
> Add new error messages

- src/qgis_gea_plugin/gui/attribute_form.py
- src/qgis_gea_plugin/gui/qgis_gea.py
Fixes https://github.com/kartoza/qgis-gea-plugin/issues/119
> Added geometry check for imported project instances

- src/qgis_gea_plugin/gui/qgis_gea.py
Follow up fix from https://github.com/kartoza/qgis-gea-plugin/pull/144
> Specify duration when showing error messages

- src/qgis_gea_plugin/data/report_templates/project_instance.qpt
- src/qgis_gea_plugin/data/report_templates/reforestation_site.qpt
- src/qgis_gea_plugin/definitions/defaults.py
- src/qgis_gea_plugin/lib/reports/generator.py
Fixes https://github.com/kartoza/qgis-gea-plugin/issues/139
> Updates on the reports templates

- src/qgis_gea_plugin/lib/reports/generator.py
Follow up fix to https://github.com/kartoza/qgis-gea-plugin/pull/142
> Map layout layers order change

- src/qgis_gea_plugin/lib/reports/generator.py
Fixes a bug that occurs when a NICFI layer is not found in the project layer tree.
Screenshot
> Fix NICFI layer checks

- .github/workflows/comment_pr_package.yml
- src/qgis_gea_plugin/lib/reports/generator.py
Updates comments actions steps to take leverage of the Github actions API.
When building pull requests packages and commenting their download url, the current workflows uses [find-comment
](https://github.com/peter-evans/find-comment) and [create-comment](https://github.com/peter-evans/create-or-update-comment). These actions steps can all be achieved by using the Github actions API.
> Commenting update

- src/qgis_gea_plugin/gui/attribute_form.py
Update the feedback message when plugin identifies a project instance  feature with an invalid geometry.
> Change instances feedback message

- README.md
Update plugin information to use the latest plugin details.
> Changed plugin information

- src/qgis_gea_plugin/gui/qgis_gea.py
- src/qgis_gea_plugin/lib/reports/manager.py
Stop QGIS UI hanging when report generation has started.
> UI lag when starting report generation
